### ISSUE TITLE
IOS reconnect issue (IPhone and IPad)

### ISSUE THREAD

**Issue by gsicilia82** [CDFER/Captive-Portal-ESP32#8]
Hi, thanks for your great work. I encounter one issue with IOS devices only:
When I connect first time with IPhone or IPad device, captive portal opens directly. When I disconnect and connect again, captive portal doesn't open again.
I have to click on "forget wifi network", afterwards it works again for one time. 

Do you have an advise how to solve this issue?

Thank you.

BTW: On Android devices everything works well, every time

**Comment by CDFER** [comment]
Hi,

Thank you for reaching out and providing feedback on the Captive Portal example. I'm glad to hear that it's working well on Android devices. I understand the issue you're experiencing with iOS devices, where the captive portal doesn't open again after disconnecting and reconnecting.

This behaviour can be related to how iOS devices handle captive portal detection and caching. To ensure a consistent experience, here are a few suggestions you can check if the issue is specific to certain versions of iOS. It's possible that Apple has made changes to how captive portal detection works in different iOS releases. Testing on different iOS versions may help identify any specific compatibility issues.

Additionally, I just recently released version 0.5.0 of the Captive Portal Example. It includes some improvements and bug fixes that might address the issue you're facing. I encourage you to try the new release and post the serial output for further analysis. The serial output can provide valuable information about the connection process and any error messages that might help diagnose the problem.

Thank you for your support and understanding. We appreciate your contribution to improving the example.

Best regards,
Chris

**Comment by gsicilia82** [comment]
Thank you for the update. I will check within next few days and let you know.
